
services:
  backend:
    container_name: navigator-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: weatherme/navigator-backend:latest
    ports:
      - "3000:3000"
    networks:
      - navigator


  frontend:
    container_name: navigator-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: weatherme/navigator-frontend:latest
    ports:
      - "8888:8888"
    networks:
      - navigator

networks:
  navigator:
    driver: bridge
